### ISSUE TITLE
GitCommit status update fails for Azure DevOps Repo

### ISSUE THREAD

**Issue by vmartinlantek** [Azure/gitops-connector#51]
Hey!

I've deployed GitOps connector with the below config:

```
gitRepositoryType: AZDO          
ciCdOrchestratorType: AZDO
gitOpsOperatorType: FLUX
azdoGitOpsRepoName: <RepoName>
azdoOrgUrl: https://dev.azure.com/<org>/<project>
orchestratorPAT: <DevOps PAT>
```

When the connector tries to update the commit status I get this error (I've ommited the sensitive parts of the URLs):

```
 2023-05-02T06:52:55.378175027Z DEBUG:urllib3.connectionpool:https://dev.azure.com:443 "POST /<org>/<project>/_apis/git/repositories/<repo>/commits/main@sha1:<sha>/statuses?api-version=6.0 HTTP/1.1" 400 227
```

If I run this request manually against DevOps I get the response:
```
{
    "$id": "1",
    "innerException": null,
    "message": "A potentially dangerous Request.Path value was detected from the client (:).",
    "typeName": "System.Web.HttpException, System.Web",
    "typeKey": "HttpException",
    "errorCode": 0,
    "eventId": 0
}
```
Full log:

```
 2023-05-02T06:52:55.405696440Z ERROR:gitops_event_handler:Exception on /gitopsphase [POST]                                                                                                                    
 ││ 2023-05-02T06:52:55.405730040Z Traceback (most recent call last):                                                                                                                                             
 ││ 2023-05-02T06:52:55.405736340Z   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app                                                                                           
 ││ 2023-05-02T06:52:55.405741040Z     response = self.full_dispatch_request()                                                                                                                                    
 ││ 2023-05-02T06:52:55.405746140Z   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request                                                                              
 ││ 2023-05-02T06:52:55.405750040Z     rv = self.handle_user_exception(e)                                                                                                                                         
 ││ 2023-05-02T06:52:55.405753340Z   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request                                                                              
 ││ 2023-05-02T06:52:55.405757940Z     rv = self.dispatch_request()                                                                                                                                               
 ││ 2023-05-02T06:52:55.405762340Z   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request                                                                                   
 ││ 2023-05-02T06:52:55.405767140Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)                                                                                               
 ││ 2023-05-02T06:52:55.405772840Z   File "/app/gitops_event_handler.py", line 33, in gitopsphase                                                                                                                 
 ││ 2023-05-02T06:52:55.405776440Z     gitops_connector.process_gitops_phase(payload, req_time)                                                                                                                   
 ││ 2023-05-02T06:52:55.405782940Z   File "/app/gitops_connector.py", line 32, in process_gitops_phase                                                                                                            
 ││ 2023-05-02T06:52:55.405786440Z     self._notify_orchestrator(phase_data, commit_id)                                                                                                                           
 ││ 2023-05-02T06:52:55.405790540Z   File "/app/gitops_connector.py", line 44, in _notify_orchestrator                                                                                                            
 ││ 2023-05-02T06:52:55.405795740Z     self._cicd_orchestrator.notify_on_deployment_completion(commit_id, is_successful)                                                                                          
 ││ 2023-05-02T06:52:55.405800740Z   File "/app/orchestrators/azdo_cicd_orchestrator.py", line 25, in notify_on_deployment_completion                                                                             
 ││ 2023-05-02T06:52:55.405805540Z     pr_num = self.git_repository.get_pr_num(commit_id)                                                                                                                         
 ││ 2023-05-02T06:52:55.405810341Z   File "/app/repositories/azdo_git_repository.py", line 125, in get_pr_num                                                                                                     
 ││ 2023-05-02T06:52:55.405814941Z     comment = self.get_commit_message(commit_id)                                                                                                                               
 ││ 2023-05-02T06:52:55.405818241Z   File "/app/repositories/azdo_git_repository.py", line 117, in get_commit_message                                                                                             
 ││ 2023-05-02T06:52:55.405821341Z     response.raise_for_status()                                                                                                                                               
 ││ 2023-05-02T06:52:55.405824841Z   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status                                                                             
 ││ 2023-05-02T06:52:55.405828741Z     raise HTTPError(http_error_msg, response=self)                                                                                                                             
 ││ 2023-05-02T06:52:55.405833541Z requests.exceptions.HTTPError: 400 Client Error: Bad Request for url:
```

**Comment by vmartinlantek** [comment]
- Closing issue as this is the same as [https://github.com/Azure/gitops-connector/issues/47](this issue)
